eureka:
  instance:
    #instanceId: dottorzibbordi
    nonSecurePort: 8080
    preferIpAddress: false
    #hostname: 192.168.50.4
    #ipAddress: 192.168.50.4
    hostname: localhost
    ipAddress: 127.0.0.1

#anarchia:
#  welcome: Ordine Senza Potere

