info:
  component: Zuul Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  routes:
    stores: /stores/**
    customers: /customers/**

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
